#!/bin/sh
# -*- mode: sh -*-
#
# SPDX-License-Identifier: LGPL-2.0+
# Copyright 2021 NXP
#
# usage:
# gstnninferencedemo-mobilenet-ssd-camera [device]

# camera device
CAMERA=/dev/video0
if [ $# = 1 ]; then
  CAMERA=$1
fi

# demo mode
DEMO_MODE=mobilenet-ssd

# NN model
MODEL=/usr/share/gstnninferencedemo/google-coral/examples-camera/mobilenet_ssd_v2_coco_quant_postprocess.tflite
LABEL=/usr/share/gstnninferencedemo/google-coral/examples-camera/coco_labels.txt

# display stats
DISPLAY_STATS=true

# enable inference (or skip inference)
ENABLE_INFERENCE=true

# use NNAPI (or use CPUs)
USE_NNAPI=false
if [ -f /proc/device-tree/model ]; then
  cat /proc/device-tree/model | grep -e "i.MX8MPlus" > /dev/null
  if [ $? = 0 ]; then
    USE_NNAPI=true
  fi
fi

# if using CPUs, set num of CPUs
NUM_THREADS=4
#NUM_THREADS=3
#NUM_THREADS=2
#NUM_THREADS=1

# rotation
ROT=horizontal-flip
#ROT=none

# video sync
SYNC=false
#SYNC=true

# camera resolution
SRC_WIDTH=1280
SRC_HEIGHT=720

# windows size
WIN_WIDTH=1280
WIN_HEIGHT=720

# debug
export VSI_NN_LOG_LEVEL=0

# gstreamer pipeline
GST_COMMAND="gst-launch-1.0 -v v4l2src device=${CAMERA} ! video/x-raw,width=${SRC_WIDTH},height=${SRC_HEIGHT} ! queue max-size-time=0 ! nninferencedemo rotation=${ROT} demo-mode=${DEMO_MODE} model=${MODEL} label=${LABEL} use-nnapi=${USE_NNAPI} num-threads=${NUM_THREADS} display-stats=${DISPLAY_STATS} enable-inference=${ENABLE_INFERENCE} ! waylandsink sync=${SYNC}"

# run
echo ${GST_COMMAND}
${GST_COMMAND}
