#!/bin/sh
# -*- mode: sh -*-
#
# SPDX-License-Identifier: LGPL-2.0+
# Copyright 2021 NXP
#
# usage:
# gstnninferencedemo-posenet-camera [device]

# camera device
CAMERA=/dev/video0
if [ $# = 1 ]; then
  CAMERA=$1
  USE_NNAPI=2
elif [ $# = 2 ]; then
  CAMERA=$1
  if [ "$2" == "--use_nnapi=true" ]; then
    USE_NNAPI=1
  elif [ "$2" == "--use_vxdelegate=true" ]; then
    USE_NNAPI=2
  else
    echo "Usage:"
    echo "# $0 </dev/videox> <--use_vxdelegate=true or --use_nnapi=true>"
    exit 1
   fi
else
  echo "Usage:"
  echo "# $0 </dev/videox>"
  exit 1
fi

# demo mode
DEMO_MODE=posenet

# NN model
MODEL=/usr/share/gstnninferencedemo/google-coral/project-posenet/posenet_mobilenet_v1_075_353_481_quant_decoder.tflite
LABEL=no-label

# display stats
DISPLAY_STATS=true

# enable inference (or skip inference)
ENABLE_INFERENCE=true

# use vx-delegate (or use NNAPI or use CPUs)
if [ -f /proc/device-tree/model ]; then
  cat /proc/device-tree/model | grep -e "i.MX8MPlus" > /dev/null
  if [ $? = 1 ]; then
    USE_NNAPI=0
  fi
fi

# if using CPUs, set num of CPUs
NUM_THREADS=4
#NUM_THREADS=3
#NUM_THREADS=2
#NUM_THREADS=1

# rotation
ROT=horizontal-flip
#ROT=none

# video sync
SYNC=false
#SYNC=true

# camera resolution
SRC_WIDTH=1280
SRC_HEIGHT=720

# windows size
WIN_WIDTH=1280
WIN_HEIGHT=720

# debug
export VSI_NN_LOG_LEVEL=0

# gstreamer pipeline
GST_COMMAND="gst-launch-1.0 -v v4l2src device=${CAMERA} ! video/x-raw,width=${SRC_WIDTH},height=${SRC_HEIGHT} ! queue max-size-time=0 ! nninferencedemo rotation=${ROT} demo-mode=${DEMO_MODE} model=${MODEL} label=${LABEL} use-nnapi=${USE_NNAPI} num-threads=${NUM_THREADS} display-stats=${DISPLAY_STATS} enable-inference=${ENABLE_INFERENCE} ! waylandsink sync=${SYNC}"

# run
echo ${GST_COMMAND}
${GST_COMMAND}
